# Generated by Django 4.1.7 on 2023-03-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratesbasedollar',
            options={'get_latest_by': ['date', 'currency__code']},
        ),
        migrations.AlterUniqueTogether(
            name='ratesbasedollar',
            unique_together={('currency', 'date')},
        ),
    ]
